[project]
name = "chess-bot"
version = "0.1.0"
description = "Code for a chess robot made from old 3D printer"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chess>=1.11.2",
    "pyserial>=3.5",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
